/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kcse_acea;

import kcse_acea.dataAnalysis.TailStatAnalyzer;

import java.io.File;
import java.io.FileReader;
import java.io.Reader;

public class Main {
    private static String path;
    private static int optCode;
    private static String repoPath;
    public static void printHelp() {
        System.out.println("Usage: [options]");

    }
    public static void main(String[] args) {
        int index = 0;
        for (String arg : args) {
            if (arg.equals("-h")) {
                printHelp();
                break;
            } else if (arg.equals("-t") || arg.equals("-tail")) {
                optCode = 0;
                path = args[index + 1];
            }
            if (arg.equals("-p")) {
                repoPath = args[index + 1];
            }
            index++;
        }
        run();
    }
    public static void run() {
        try {
            Reader in = new FileReader(path);
            if (optCode == 0) {
                TailStatAnalyzer tailStat = new TailStatAnalyzer(in);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }


}
